apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  # Pick address range outside of kind usage
  # docker network inspect kind | jq '.[].IPAM.Config[].Subnet'
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 172.18.255.1-172.18.255.250
