---
apiVersion: v1
kind: Service
metadata:
  name: flux
  namespace: flux
  labels:
    name: flux
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 3031
      targetPort: 3031
  selector:
    name: flux
