# https://metallb.universe.tf/installation/
# kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"
apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
data:
  secretkey: Skp6UjQ4M0haSUFLblNQREVuRzdGeGRFeXh6TVpqNis4R3FuOVpWRkdEMGVlWWxjdmUvR0Jab3lrUWZrMjVTdQpWLzdDS05ZQmZJenljaU04Ryt4cGFtNTMzU1NMRmpDSUhtTTNydkx6dGVPczM3VVNhZ3FjRm5mTmpFR0hHZlJUCm9PdlozTjU3UUdKQkF4V0lHbmN6dm55YlIxNFY0Wit6eXMvQTdWWFVyR009
