apiVersion: v1
data:
  alertmanager.yaml: Z2xvYmFsOgogIHJlc29sdmVfdGltZW91dDogNW0Kcm91dGU6CiAgZ3JvdXBfYnk6IFsnam9iJ10KICBncm91cF93YWl0OiAzMHMKICBncm91cF9pbnRlcnZhbDogNW0KICByZXBlYXRfaW50ZXJ2YWw6IDEyaAogIHJlY2VpdmVyOiAnbnVsbCcKICByb3V0ZXM6CiAgIyBUaGluZ3Mgd2UgbmV2ZXIgd2FudCB0byBhbGVydCBvbiBpbiBvdXIgZW52aXJvbm1lbnQKICAtIG1hdGNoX3JlOgogICAgICBhbGVydG5hbWU6IERlYWRNYW5zU3dpdGNofFdhdGNoZG9nCiAgICByZWNlaXZlcjogJ251bGwnCiAgLSBtYXRjaF9yZToKICAgICAgYWxlcnRuYW1lOiBLdWJlVmVyc2lvbk1pc21hdGNofEt1YmVDb250cm9sbGVyTWFuYWdlckRvd258S3ViZVNjaGVkdWxlckRvd24KICAgIHJlY2VpdmVyOiAnbnVsbCcKICAtIG1hdGNoX3JlOgogICAgICBhbGVydG5hbWU6IFByb21ldGhldXNEdXBsaWNhdGVUaW1lc3RhbXBzfFByb21ldGhldXNPdXRPZk9yZGVyVGltZXN0YW1wcwogICAgcmVjZWl2ZXI6ICdudWxsJwoKaW5oaWJpdF9ydWxlczoKLSBzb3VyY2VfbWF0Y2g6CiAgICBzZXZlcml0eTogJ2NyaXRpY2FsJwogIHRhcmdldF9tYXRjaDoKICAgIHNldmVyaXR5OiAnd2FybmluZycKICBlcXVhbDogWydhbGVydG5hbWUnXQoKcmVjZWl2ZXJzOgotIG5hbWU6ICdudWxsJwo=
kind: Secret
metadata:
  name: alertmanager-main
  namespace: monitoring
type: Opaque
